version: '2'

services:
    wrangler:
        build:
            context: ./data_preparation
    
    trainer:
        build:
            context: ./data/train
    
networks:
    titanicapp-network
    driver: bridge